// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCglC9Zpx41Hc06-G77cEWoxRNX7Gmv3R4',
    appId: '1:352266667037:web:4727cd996c058ac230f2f4',
    messagingSenderId: '352266667037',
    projectId: 'blog-84a2a',
    authDomain: 'blog-84a2a.firebaseapp.com',
    storageBucket: 'blog-84a2a.firebasestorage.app',
    measurementId: 'G-491L9DCN8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJEZsnqsEwbaLoC-hcW1AXBrmvRtiYq88',
    appId: '1:352266667037:android:f25b17eea6537e2f30f2f4',
    messagingSenderId: '352266667037',
    projectId: 'blog-84a2a',
    storageBucket: 'blog-84a2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS2-E52MLq2ZjxmhQGm-eeAsaVgXlCSbA',
    appId: '1:352266667037:ios:71aa377f0cf2f69b30f2f4',
    messagingSenderId: '352266667037',
    projectId: 'blog-84a2a',
    storageBucket: 'blog-84a2a.firebasestorage.app',
    iosBundleId: 'com.example.outLoud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS2-E52MLq2ZjxmhQGm-eeAsaVgXlCSbA',
    appId: '1:352266667037:ios:71aa377f0cf2f69b30f2f4',
    messagingSenderId: '352266667037',
    projectId: 'blog-84a2a',
    storageBucket: 'blog-84a2a.firebasestorage.app',
    iosBundleId: 'com.example.outLoud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCglC9Zpx41Hc06-G77cEWoxRNX7Gmv3R4',
    appId: '1:352266667037:web:2cfe90b51dd9895730f2f4',
    messagingSenderId: '352266667037',
    projectId: 'blog-84a2a',
    authDomain: 'blog-84a2a.firebaseapp.com',
    storageBucket: 'blog-84a2a.firebasestorage.app',
    measurementId: 'G-L3KQXJJJKT',
  );
}
